# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i1-iJgAqLKd6j5M7rOyUtALwAgX4lnlT
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

IrisData = pd.read_csv("listings.csv")
print(IrisData.dtypes)
print(IrisData.isna().values.any())

newIrisDataCont = IrisData[["latitude", "longitude", "price", "number_of_reviews", "reviews_per_month", "calculated_host_listings_count", "availability_365"]]
newIrisDataDisc = IrisData[["minimum_nights"]]

print("Continuous Data : \n\n{}\n".format(newIrisDataCont.head()))
print("Discrete Data : \n\n{}".format(newIrisDataDisc.head()))

print("Mean of Continuous Data = \n{}\n\n".format(newIrisDataCont.mean()))
print("Variance of Continuous Data = \n{}\n\n".format(np.var(newIrisDataCont)))

print("Mean of Discrete Data = \n{}\n\n".format(newIrisDataDisc.mean()))
print("Variance of Continuous Data = \n{}\n\n".format(np.var(newIrisDataDisc)))