# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EuJS0hXbFW1DzUFUOKtmpQE63Tdy0EBO
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
irisData = pd.read_csv("listings.csv", delimiter = ",")
print(irisData.head())

data = pd.DataFrame(irisData)
minValue = data.min()
print(minValue)

data = pd.DataFrame(irisData)
maxValue = data.max()
print(maxValue)

irisData.shape
modifiedIrisData = irisData.dropna()
modifiedIrisData.isnull().sum()

irisData.shape
modifiedIrisDataReplace = irisData.fillna(" ")
modifiedIrisDataReplace.isnull().sum()